### ISSUE TITLE
Type error when using strictTemplates

### ISSUE THREAD

**Issue by snebjorn** [TNG/ngx-structurals#23]
Getting this type error when running with `"angularCompilerOptions": { "strictTemplates": true }`

    ERROR in src/app/components/side-menu/side-menu.component.html:11:15 - error TS2322: Type 'string' is not assignable to type 'Observable<boolean>'.
    
    11 <ng-container *ngxSubscribe="let isSideMenuCollapsed of isSideMenuCollapsed$">
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Component**
```ts
export class SideMenuComponent {
  // type is Observable<boolean> and is coming from an Akita query
  public readonly isSideMenuCollapsed$ = this.sideMenuQuery.isSideMenuCollapsed$;

  ...
}
```

**HTML**
```html
<ng-container *ngxSubscribe="let isSideMenuCollapsed of isSideMenuCollapsed$">
   ...
</ng-container>
```

**UPDATE**
This works
`<ng-container *ngxAlias="isSideMenuCollapsed$ | async as isSideMenuCollapsed">`
Perhaps it's not related to strictTemplates but me misunderstanding  `ngxSubscribe`

**Comment by Airblader** [comment]
Thanks for opening this issue (and sorry for accidentally closing it for a second there)!

I believe that this is the following language service issue I've raised last year: https://github.com/angular/vscode-ng-language-service/issues/651

Unfortunately until that is fixed in the language service I don't think there is much we can do from library side.

**Comment by ayazhafiz** [comment]
This happens because the desugared form of `<ng-container *ngxSubscribe="let isSideMenuCollapsed of isSideMenuCollapsed$">{{isSideMenuCollapsed}}</ng-container>` is

```html
<ng-template ngxSubscribe let-isSideMenuCollapsed [ngxSubscribeOf]="isSideMenuCollapsed$">
  <ng-container>{{isSideMenuCollapsed}}</ng-container>
</ng-template>
```

The interesting part is that `ngxSubscribe` plays two roles -- it is both the [selector](https://github.com/TNG/ngx-structurals/blob/master/projects/ngx-structurals/src/lib/ngx-subscribe/ngx-subscribe.directive.ts#L64) for the `NgxSubscribeDirective` and an [input](https://github.com/TNG/ngx-structurals/blob/1dfa7fc722f36b559dd5e378ba74143613314d42/projects/ngx-structurals/src/lib/ngx-subscribe/ngx-subscribe.directive.ts#L106-L107) to the directive. In the above template, the Angular compiler further expands the desugared form to be

```html
<ng-container ngxSubscribe="" let-isSideMenuCollapsed="$implicit" [ngxSubscribeOf]="isSideMenuCollapsed$">
  <ng-container>{{isSideMenuCollapsed}}</ng-container>
</ng-template>
```

So the value passed to the `ngxSubscribe` input is an empty string.

A user can work around this by specifying the desugared form of the structural directive explicitly, something like

```html
<ng-container ngxSubscribe [ngxSubscribe]="myDummyObservable" let-isSideMenuCollapsed [ngxSubscribeOf]="isSideMenuCollapsed$">
  <ng-container>{{isSideMenuCollapsed}}</ng-container>
</ng-template>
```

One solution for the library side is to remove the `ngxSubscribe` input or to break up the `*ngxSubscribe="let data of data$"` and `*ngxSubscribe="data$; then thenTemplate ..."` use cases into two separate directives.

**Comment by snebjorn** [comment]
I'm not sure I completely understand. I thought language services were used to make squiggles in editors.

Doesn't the error come from the angular compiler?

**Comment by ayazhafiz** [comment]
Yes, this is a compile error and unrelated to the language service.

**Comment by Airblader** [comment]
Thanks @ayazhafiz, I really appreciate your input on this, and sorry for the confusion with the language service issue. It is rather unfortunate that the compiler expands it to an empty string, but nothing we can do about that for now.

I'll use this issue so that for now we update the docs on how the directive needs to be used (and why).

@snebjorn Sorry for the inconvenience here, but by using the desuggared form directly you should have a way to proceed, right?

**Comment by snebjorn** [comment]
I was able to proceed in this specific case using `ngxAlias` but I'll soon need the template support from `ngxSubscribe`. I'll report back when I've tried that out

**Comment by Airblader** [comment]
Actually we can probably for the ngxSubscribe input also accept string and simply do nothing if a string was passed. That should make the typings happy.

**Comment by Airblader** [comment]
@snebjorn I've released this as version 1.1.1. Can you give it a try to see if it resolves your issue?

**Comment by snebjorn** [comment]
I can confirm it works! 🚀

**Comment by Airblader** [comment]
Awesome, thanks for confirming!
